### ISSUE TITLE
Populate needed software for lab provisioning

### ISSUE THREAD

**Issue by phentos** [tritonhacks/TH24-NatureHuntStarter#2]
As a comment on this issue, please provide what software hackers will need already installed on their lab computers (if nothing is needed, state so).

**Comment by deeg-p23** [comment]
### Editors:
- Unity Hub
- Unity Version 2022.3.4f1
- Visual Studio 2022 _(recommended)_

### VCS:
- Github Desktop _(recommended)_

**Comment by phentos** [comment]
Submitted
